apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.image.name }}
    versiontag: {{ .Values.image.tag }}
spec:
  sessionAffinity: None
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ .Values.image.name }}
    version: ""
