apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-sample
  labels:
    app: app-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-sample
  template:
    metadata:
      labels:
        app: app-sample
    spec:
      containers:
      - name: app-sample
        image: k0001.azurecr.io/app_sample:cb3
        ports:
        - containerPort: 8080

